// Code generated by MockGen. DO NOT EDIT.
// Source: config/manager.go

// Package mock_config is a generated GoMock package.
package mock_config

import (
	gomock "github.com/golang/mock/gomock"
	config "github.com/nori-io/nori-common/v2/config"
	meta "github.com/nori-io/nori-common/v2/meta"
	reflect "reflect"
)

// MockManager is a mock of Manager interface
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
}

// MockManagerMockRecorder is the mock recorder for MockManager
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	return m.recorder
}

// Register mocks base method
func (m *MockManager) Register(arg0 meta.Meta) config.Config {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", arg0)
	ret0, _ := ret[0].(config.Config)
	return ret0
}

// Register indicates an expected call of Register
func (mr *MockManagerMockRecorder) Register(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockManager)(nil).Register), arg0)
}

// PluginVariables mocks base method
func (m *MockManager) PluginVariables(id meta.ID) []config.Variable {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PluginVariables", id)
	ret0, _ := ret[0].([]config.Variable)
	return ret0
}

// PluginVariables indicates an expected call of PluginVariables
func (mr *MockManagerMockRecorder) PluginVariables(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PluginVariables", reflect.TypeOf((*MockManager)(nil).PluginVariables), id)
}

// MockConfig is a mock of Config interface
type MockConfig struct {
	ctrl     *gomock.Controller
	recorder *MockConfigMockRecorder
}

// MockConfigMockRecorder is the mock recorder for MockConfig
type MockConfigMockRecorder struct {
	mock *MockConfig
}

// NewMockConfig creates a new mock instance
func NewMockConfig(ctrl *gomock.Controller) *MockConfig {
	mock := &MockConfig{ctrl: ctrl}
	mock.recorder = &MockConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockConfig) EXPECT() *MockConfigMockRecorder {
	return m.recorder
}

// Bool mocks base method
func (m *MockConfig) Bool(key, desc string) config.Bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bool", key, desc)
	ret0, _ := ret[0].(config.Bool)
	return ret0
}

// Bool indicates an expected call of Bool
func (mr *MockConfigMockRecorder) Bool(key, desc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bool", reflect.TypeOf((*MockConfig)(nil).Bool), key, desc)
}

// Float mocks base method
func (m *MockConfig) Float(key, desc string) config.Float {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Float", key, desc)
	ret0, _ := ret[0].(config.Float)
	return ret0
}

// Float indicates an expected call of Float
func (mr *MockConfigMockRecorder) Float(key, desc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Float", reflect.TypeOf((*MockConfig)(nil).Float), key, desc)
}

// Int mocks base method
func (m *MockConfig) Int(key, desc string) config.Int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Int", key, desc)
	ret0, _ := ret[0].(config.Int)
	return ret0
}

// Int indicates an expected call of Int
func (mr *MockConfigMockRecorder) Int(key, desc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Int", reflect.TypeOf((*MockConfig)(nil).Int), key, desc)
}

// Int8 mocks base method
func (m *MockConfig) Int8(key, desc string) config.Int8 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Int8", key, desc)
	ret0, _ := ret[0].(config.Int8)
	return ret0
}

// Int8 indicates an expected call of Int8
func (mr *MockConfigMockRecorder) Int8(key, desc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Int8", reflect.TypeOf((*MockConfig)(nil).Int8), key, desc)
}

// Int32 mocks base method
func (m *MockConfig) Int32(key, desc string) config.Int32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Int32", key, desc)
	ret0, _ := ret[0].(config.Int32)
	return ret0
}

// Int32 indicates an expected call of Int32
func (mr *MockConfigMockRecorder) Int32(key, desc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Int32", reflect.TypeOf((*MockConfig)(nil).Int32), key, desc)
}

// Int64 mocks base method
func (m *MockConfig) Int64(key, desc string) config.Int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Int64", key, desc)
	ret0, _ := ret[0].(config.Int64)
	return ret0
}

// Int64 indicates an expected call of Int64
func (mr *MockConfigMockRecorder) Int64(key, desc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Int64", reflect.TypeOf((*MockConfig)(nil).Int64), key, desc)
}

// UInt mocks base method
func (m *MockConfig) UInt(key, desc string) config.UInt {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UInt", key, desc)
	ret0, _ := ret[0].(config.UInt)
	return ret0
}

// UInt indicates an expected call of UInt
func (mr *MockConfigMockRecorder) UInt(key, desc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UInt", reflect.TypeOf((*MockConfig)(nil).UInt), key, desc)
}

// UInt32 mocks base method
func (m *MockConfig) UInt32(key, desc string) config.UInt32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UInt32", key, desc)
	ret0, _ := ret[0].(config.UInt32)
	return ret0
}

// UInt32 indicates an expected call of UInt32
func (mr *MockConfigMockRecorder) UInt32(key, desc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UInt32", reflect.TypeOf((*MockConfig)(nil).UInt32), key, desc)
}

// UInt64 mocks base method
func (m *MockConfig) UInt64(key, desc string) config.UInt64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UInt64", key, desc)
	ret0, _ := ret[0].(config.UInt64)
	return ret0
}

// UInt64 indicates an expected call of UInt64
func (mr *MockConfigMockRecorder) UInt64(key, desc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UInt64", reflect.TypeOf((*MockConfig)(nil).UInt64), key, desc)
}

// Slice mocks base method
func (m *MockConfig) Slice(key, desc string) config.Slice {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Slice", key, desc)
	ret0, _ := ret[0].(config.Slice)
	return ret0
}

// Slice indicates an expected call of Slice
func (mr *MockConfigMockRecorder) Slice(key, desc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Slice", reflect.TypeOf((*MockConfig)(nil).Slice), key, desc)
}

// SliceInt mocks base method
func (m *MockConfig) SliceInt(key, desc string) config.SliceInt {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SliceInt", key, desc)
	ret0, _ := ret[0].(config.SliceInt)
	return ret0
}

// SliceInt indicates an expected call of SliceInt
func (mr *MockConfigMockRecorder) SliceInt(key, desc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SliceInt", reflect.TypeOf((*MockConfig)(nil).SliceInt), key, desc)
}

// SliceString mocks base method
func (m *MockConfig) SliceString(key, desc string) config.SliceString {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SliceString", key, desc)
	ret0, _ := ret[0].(config.SliceString)
	return ret0
}

// SliceString indicates an expected call of SliceString
func (mr *MockConfigMockRecorder) SliceString(key, desc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SliceString", reflect.TypeOf((*MockConfig)(nil).SliceString), key, desc)
}

// String mocks base method
func (m *MockConfig) String(key, desc string) config.String {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String", key, desc)
	ret0, _ := ret[0].(config.String)
	return ret0
}

// String indicates an expected call of String
func (mr *MockConfigMockRecorder) String(key, desc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockConfig)(nil).String), key, desc)
}

// StringMap mocks base method
func (m *MockConfig) StringMap(key, desc string) config.StringMap {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StringMap", key, desc)
	ret0, _ := ret[0].(config.StringMap)
	return ret0
}

// StringMap indicates an expected call of StringMap
func (mr *MockConfigMockRecorder) StringMap(key, desc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StringMap", reflect.TypeOf((*MockConfig)(nil).StringMap), key, desc)
}

// StringMapInt mocks base method
func (m *MockConfig) StringMapInt(key, desc string) config.StringMapInt {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StringMapInt", key, desc)
	ret0, _ := ret[0].(config.StringMapInt)
	return ret0
}

// StringMapInt indicates an expected call of StringMapInt
func (mr *MockConfigMockRecorder) StringMapInt(key, desc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StringMapInt", reflect.TypeOf((*MockConfig)(nil).StringMapInt), key, desc)
}

// StringMapSliceString mocks base method
func (m *MockConfig) StringMapSliceString(key, desc string) config.StringMapSliceString {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StringMapSliceString", key, desc)
	ret0, _ := ret[0].(config.StringMapSliceString)
	return ret0
}

// StringMapSliceString indicates an expected call of StringMapSliceString
func (mr *MockConfigMockRecorder) StringMapSliceString(key, desc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StringMapSliceString", reflect.TypeOf((*MockConfig)(nil).StringMapSliceString), key, desc)
}

// StringMapString mocks base method
func (m *MockConfig) StringMapString(key, desc string) config.StringMapString {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StringMapString", key, desc)
	ret0, _ := ret[0].(config.StringMapString)
	return ret0
}

// StringMapString indicates an expected call of StringMapString
func (mr *MockConfigMockRecorder) StringMapString(key, desc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StringMapString", reflect.TypeOf((*MockConfig)(nil).StringMapString), key, desc)
}
