// Code generated by mockery v1.0.0. DO NOT EDIT.

//
/*
Copyright 2019 The Nori Authors.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package mocks

import context "context"
import http "github.com/nori-io/nori-common/transport/http"
import interfaces "github.com/nori-io/nori-common/interfaces"
import mock "github.com/stretchr/testify/mock"
import nethttp "net/http"

// HTTPTransport is an autogenerated mock type for the HTTPTransport type
type HTTPTransport struct {
	mock.Mock
}

// ToContext provides a mock function with given fields:
func (_m *HTTPTransport) ToContext() http.ServerBeforeFunc {
	ret := _m.Called()

	var r0 http.ServerBeforeFunc
	if rf, ok := ret.Get(0).(func() http.ServerBeforeFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.ServerBeforeFunc)
		}
	}

	return r0
}

// ToTransport provides a mock function with given fields: ctx, w, at
func (_m *HTTPTransport) ToTransport(ctx context.Context, w nethttp.ResponseWriter, at interfaces.AccessTokener) http.ServerAfterFunc {
	ret := _m.Called(ctx, w, at)

	var r0 http.ServerAfterFunc
	if rf, ok := ret.Get(0).(func(context.Context, nethttp.ResponseWriter, interfaces.AccessTokener) http.ServerAfterFunc); ok {
		r0 = rf(ctx, w, at)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.ServerAfterFunc)
		}
	}

	return r0
}
