// Code generated by mockery v1.0.0. DO NOT EDIT.

//
/*
Copyright 2019 The Nori Authors.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package mocks

import config "github.com/nori-io/nori-common/config"
import meta "github.com/nori-io/nori-common/meta"
import mock "github.com/stretchr/testify/mock"

// Manager is an autogenerated mock type for the Manager type
type Manager struct {
	mock.Mock
}

// PluginVariables provides a mock function with given fields: id
func (_m *Manager) PluginVariables(id meta.ID) []config.Variable {
	ret := _m.Called(id)

	var r0 []config.Variable
	if rf, ok := ret.Get(0).(func(meta.ID) []config.Variable); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]config.Variable)
		}
	}

	return r0
}

// Register provides a mock function with given fields: _a0
func (_m *Manager) Register(_a0 meta.Meta) config.Config {
	ret := _m.Called(_a0)

	var r0 config.Config
	if rf, ok := ret.Get(0).(func(meta.Meta) config.Config); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.Config)
		}
	}

	return r0
}
