// Code generated by mockery v1.0.0. DO NOT EDIT.

//
/*
Copyright 2019 The Nori Authors.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package mocks

import interfaces "github.com/nori-io/nori-common/interfaces"
import mock "github.com/stretchr/testify/mock"
import sql "database/sql"

// SQL is an autogenerated mock type for the SQL type
type SQL struct {
	mock.Mock
}

// GetDB provides a mock function with given fields:
func (_m *SQL) GetDB() *sql.DB {
	ret := _m.Called()

	var r0 *sql.DB
	if rf, ok := ret.Get(0).(func() *sql.DB); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.DB)
		}
	}

	return r0
}

// GetRDBMSInfo provides a mock function with given fields:
func (_m *SQL) GetRDBMSInfo() interfaces.RDBMSInfo {
	ret := _m.Called()

	var r0 interfaces.RDBMSInfo
	if rf, ok := ret.Get(0).(func() interfaces.RDBMSInfo); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(interfaces.RDBMSInfo)
	}

	return r0
}
